baseURL = 'https://acmgazi.com/'
languageCode = "tr"
title = 'ACM Gazi'
theme = 'ananke'
favicon = '/static/images/favicon.png'
pluralizeListTitles = false

[params]
description = "Gazi Üniversitesi Bilgisayar Makineleri Birliği (ACM) Öğrenci Topluluğu resmi web sitesi"
