backend:
  name: github
  repo: acm-gazi/acm-gazi.github.io
  branch: main
  base_url: https://sveltia-cms-auth.qewer.workers.dev/
media_folder: static/img
public_folder: /img
collections:
  - name: 'haberler'
    label: 'Haberler'
    folder: 'content/haberler'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Başlık', name: 'title', widget: 'string' }
      - { label: 'Yayınlanma Tarihi', name: 'date', widget: 'datetime' }
      - { label: 'Metin', name: 'body', widget: 'markdown' }
    media_folder: /static/media/haberler
  - name: 'etkinlikler'
    label: 'Etkinlikler'
    folder: 'content/etkinlikler'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Başlık', name: 'title', widget: 'string' }
      - { label: 'Resim', name: 'featured_image', widget: 'image' }
      - { label: 'Etkinlik Tarihi', name: 'date', widget: 'datetime' }
      - { label: 'Metin', name: 'body', widget: 'markdown' }
    media_folder: /static/media/etkinlikler
  - name: 'sponsorlar'
    label: 'Sponsorlar'
    folder: 'content/sponsorlar'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'İsin', name: 'name', widget: 'string' }
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Tier', name: 'tier', widget: 'select', options: ['Altın', 'Gümüş', 'Bronz'] }
    media_folder: /static/media/sponsorlar