backend:
  name: github
  repo: qewer33/acmgaziweb
media_folder: static/img
public_folder: /img
collections:
  - name: 'haberler'
    label: 'Haberler'
    folder: 'content/haberler'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Başlık', name: 'title', widget: 'string' }
      - { label: 'Yayınlanma Zamanı', name: 'date', widget: 'datetime' }
      - { label: 'Metin', name: 'body', widget: 'markdown' }
    media_folder: /static/media/haberler
  - name: 'etkinlikler'
    label: 'Etkinlikler'
    folder: 'content/etkinlikler'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Başlık', name: 'title', widget: 'string' }
      - { label: 'Resim', name: 'featured_image', widget: 'image' }
      - { label: 'Metin', name: 'body', widget: 'markdown' }
    media_folder: /static/media/etkinlikler